config/routes.rb
Rails.application.routes.draw do
  # Home page should direct to the sales index page.
  root 'sales#index'

  # Routes for sessions.
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Routes for users.
  resources :users, except: [:index] do
    collection do 
      get ':id/store', to: 'users#store', as: 'store'
    end
  end
  
  get 'signup', to: 'users#new', as: 'signup'  
  
  # Sale resource.
  resources :sales, except: [:destroy]
  
  #resources :bids, only: [:destroy]
  post 'create_bid', to: 'bids#create', as: 'create_bid'
end

app/models/user.rb
class User < ApplicationRecord
  # A User has a username/password. A User's username is unique.
  has_secure_password
  validates :username, presence: true, uniqueness: true
  # A User that is a seller has many sales.
  has_many :sales, foreign_key: "seller_id", class_name: "Sale"
  # A User that is a buyer has many bids.
  has_many :bids

  # Get a list of the Sales a Buyer has Bid on.
  def get_sales_as_bidder
    self.bids.map {|bid| bid.sale}.select {|sale| sale.active}.uniq
  end

  # Get a list of the Sales a Seller has posted.
  def open_sales
    self.sales.select {|sale| sale.active }
  end

  # Get a list of a Seller's Sales that found a buyer.
  def get_successful_sales
    self.sales.select {|sale| !sale.active && sale.owner_id != self.id}
  end

  # Get a list of the Sales whose auction a Buyer won.
  def won_sales
    Sale.all.select {|sale| !sale.active && sale.owner_id == self.id && self.id != sale.seller_id}
  end

  # Gets the total revenue a Seller has made from successful Sales.
  def get_total_revenue
    self.get_successful_sales.sum {|sale| sale.get_last_bid.amount}
  end

  # Gets the success rate of a Seller's Sales.
  def sale_success_rate
    self.get_successful_sales.count.to_f / self.sales.count
  end

  # Get the Seller's Sale that received the most Bids.
  def most_popular_sale
    self.get_successful_sales.max_by {|sale| sale.bids.count}
  end

  # Get a list of the Seller's Sales that were not Bid on.
  def get_unsuccessful_sales
    (self.sales - self.get_successful_sales).select {|sale| !sale.active}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Before showing, editing, updating, or destroying a user, look them up.
  before_action :set_user, only: [:show, :edit, :update, :store]

  # Gets the show page for a User.
  # GET /users/:id
  def show
    if @user.id != current_user.id
      redirect_to store_users_path(@user)
    else
      @bidded_sales = @user.get_sales_as_bidder.sort_by {|sale| sale.bids.last.created_at}
    end
  end

  # Gets the page containing a form to create a new User.
  # GET /users/new
  def new
    @user = User.new
  end

  # Creates a new User with form input.
  # POST /
  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account successfully created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "Account successfully updated!"
    else
      render 'edit'
    end
  end

  # Takes us to a User's store page (show page for sellers).
  # GET /users/:id/store
  def store
    @popular = @user.most_popular_sale
  end

  private
    # Finds a User based on the :id parameter passed to the route.
    def set_user
      @user = User.find(params[:id])
    end

    # Censor the params to make sure no bad guys take control of our app.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_feed.html.erb
<div class="ui large feed">
  <% @user.won_sales.each do |sale| %>
    <div class="event">
      <div class="label">
        <img class="ui fluid rounded image" src="<%= url_for(sale.img) if sale.img.attached?%>">
      </div>
      <div class="content">
        <div class="summary">
        You purchased <%= link_to sale.name, sale %> 
          <div class="date">
            on <%= sale.get_closing_date %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_stats.html.erb
<div class="ui grid">
  <div class="eight wide centered column">
    <div class="ui segments">


    <div class="ui segment">
      <h3> Your store's total revenue: $<%=@user.get_total_revenue %></h3>
    </div>
    <% if @popular %>
    <div class="ui segment">
      <h3> Most popular sale: </h3>
      <%=link_to @popular.name, @popular %> for <%= @popular.current_asking_price%> </p>
    </div>
    <% end %>
    <div class="ui segment">

    </div>
    </div>
  </div>

<div class="four wide centered column">


  <p> Unsuccessful Sales: </p>

  <div class="ui feed">
   <% @user.get_unsuccessful_sales.each do |sale| %>
     <div class="event">


      <div class="label">
        <img class="ui fluid rounded image" src="<%= url_for(sale.img) if sale.img.attached?%>">
      </div>
    <div class="content">
      <div class="summary">
      Sale for <%= link_to sale.name, sale %> closed with no bids
        <div class="date">
          on <%= sale.get_closing_date %>
        </div>
      </div>
    </div>
    </div>
    <% end %>
  </div>
  </div>


</div>

app/views/users/edit.html.erb
<div class="twelve wide centered column">
  <%= render 'assets/edit_user_form', user: @user %>
</div>

app/views/users/new.html.erb
  <%= render 'assets/user_form', user: @user %>

app/views/users/show.html.erb
<div class="twelve wide centered column">
  <h2>Hello, <%= @user.username %>!</h2>
  <div class="ui two column horizontally divided grid">
    
    <div class="six wide column">
      <h3>Your purchase history:</h3>
      <%= render 'assets/purchase_history_feed', user: @user %>
    </div>
    
    <div class="ten wide column">
      <h3>Your active auctions:</h3>
      <div class="ui large feed">
        <% @bidded_sales.each do |sale| %>
          <div class="event">
            
            <div class="label">
              <img class="ui fluid rounded image" src="<%= url_for(sale.img) if sale.img.attached? %>">
            </div>
            
            <div class="content">
              
              <div class="summary">
                Most recent bids on <%= link_to sale.name, sale %>:
                <div class="date">
                  updated on <%= sale.get_last_bid.get_time_placed %>
                </div>
              </div>
              
              <div class="extra text">
                <%= render 'assets/bids_feed', bids: sale.get_recent_bids(5) %>
              </div>
            
            </div>
          
          </div>
        <% end %>
      </div>
    </div>
  
  </div>

  <%= link_to "Edit my account", edit_user_path(@user), class: "ui semantic button" %>
</div>

app/views/users/store.html.erb
<div class="twelve wide centered column">
  <% if current_user == @user %>
    <%= render 'assets/seller_stats' %>
    <h2>Your booty:</h2>
    <% if current_user.sales.count == 0 %>
      <p style="font-size: large"> 
        You currently don't have anything up for auction!
        You can click <%= link_to "here", new_sale_path %> or Sell on the sidebar to get started!
      </p>
    <% end %>
  <% else %>
    <h2><%= @user.username %>'s booty:</h2>
  <% end %>
  
  <div class="ui five stackable cards">
    <% @user.sales.each do |sale| %>
      <%= render 'assets/sale_card', sale: sale %>
    <% end %>
  </div>
</div>