config/routes.rb
Rails.application.routes.draw do
  # Home page should direct to the sales index page.
  root 'sales#index'

  # Routes for sessions.
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Routes for users.
  resources :users, except: [:index] do
    collection do 
      get ':id/store', to: 'users#store', as: 'store'
    end
  end
  
  get 'signup', to: 'users#new', as: 'signup'  
  
  # Sale resource.
  resources :sales, except: [:destroy]
  
  #resources :bids, only: [:destroy]
  post 'create_bid', to: 'bids#create', as: 'create_bid'
end

app/views/assets/_bids.html.erb
<div class="ui small feed">
  <% bids.each do |bid| %>
    <div class="event">
      <div class="content">
        <div class="summary">
          <a class="user">
            <%= bid.username %>
          </a> placed a bid of $<%= bid.amount %>
          <div class="date">
            on <%= bid.get_time_placed %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/assets/_bids_feed.html.erb
<div class="ui small feed">
  <% bids.each do |bid| %>
    <div class="event">
      <div class="content">
        <div class="summary">
          <a class="user">
            <%= bid.username %>
          </a> placed a bid of $<%= bid.amount %>
          <div class="date">
            on <%= bid.get_time_placed %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/assets/_card.html.erb
<a class="ui raised card" href=<%= sale_path(sale) %>>
    <div class="center aligned content">
      <div class="header" id="name-font"><%= sale.name %></div>
      <div class="meta">
        <span class="category">Seller name: <%= sale.seller.username %></span>
      </div>
      <div class="description">
      <p>Current price: $<%= sale.current_asking_price %></p>
      </div>
    </div>
    <img class="ui fluid image" src="<%= url_for(sale.img) if sale.img.attached?%>">
  </a> 

app/views/assets/_edit_user_form.html.erb
<div class="update-page">
    <% if user.errors.any? %>
        <div id="error_explanation">
            <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
    <div class="form">
      <%= form_with model: user, local: true, class: "register-form" do |f| %>
        <%= f.text_field :username, placeholder: "username" %>
        <%= f.password_field :password, placeholder: "password" %>
        <%= f.password_field :password_confirmation, placeholder: "password confirmation" %>
        <%= f.submit "UPDATE", class: "buttonnn" %>
      <% end %>
    </div>
  </div>

app/views/assets/_new_sale_form.html.erb
<% if sale.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%=form_with model: sale, class: "ui form" do |f| %>
  
  <div class="five wide required field">
    <div class="ui labeled input">
      <%= f.label "Item name", class: "ui label" %>
      <%= f.text_field :name, placeholder: "Name" %>
    </div>
  </div>

  <div class="fourteen wide required field">
    <div class="ui labeled input">
    <%= f.label :description, class: "ui label" %>
    <%= f.text_area :description, placeholder: "Description" %>
    </div>
  </div>

  <div class="four wide required field">
    <div class="ui labeled input">
      <%= f.label "Starting bid", class: "ui label" %>
      <%= f.number_field :price, placeholder: "0.00" %>
    </div>
  </div>

  <div class="seven wide required field">
    <div class="ui labeled input">
      <%= f.label :closing_date, class: "ui label" %>
      <%= f.datetime_field :closing_date, min: Time.zone.now %>
    </div>
  </div>
  
  <div class="required field">
    <div class="ui labeled input">
      <%= f.label "Image", class: "ui label" %>
      <%= f.file_field :img %>
    </div>
  </div>

  <%= f.submit class: "ui teal button"%>

<% end %>

app/views/assets/_purchase_history_feed.html.erb
<div class="ui large feed">
  <% @user.won_sales.each do |sale| %>
    <div class="event">
      
      <div class="label">
        <img class="ui fluid rounded image" src="<%= url_for(sale.img) if sale.img.attached? %>">
      </div>
      
      <div class="content">
        
        <div class="summary">
          You purchased <%= link_to sale.name, sale %> 
          <div class="date">
            on <%= sale.get_closing_date %>
          </div>
        </div>
      
      </div>
    
    </div>
  <% end %>
</div>

app/views/assets/_sale_card.html.erb
<a class="ui raised card" href=<%= sale_path(sale) %>>
    <div class="center aligned content">
      <div class="header" id="name-font"><%= sale.name %></div>
      <div class="meta">
        <span class="category">Seller name: <%= sale.seller.username %></span>
      </div>
      <div class="description">
      <p>Current price: $<%= sale.current_asking_price %></p>
      </div>
    </div>
    <img class="ui small image" src="<%= url_for(sale.img) if sale.img.attached? %>">
  </a>

app/views/assets/_sale_form.html.erb
<% if sale.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%=form_with model: sale, class: "ui form" do |f| %>
  
  <div class="five wide required field">
    <div class="ui labeled input">
      <%= f.label "Item name", class: "ui label" %>
      <%= f.text_field :name, placeholder: "Name" %>
    </div>
  </div>

  <div class="fourteen wide required field">
    <div class="ui labeled input">
    <%= f.label :description, class: "ui label" %>
    <%= f.text_area :description, placeholder: "Description" %>
    </div>
  </div>

  <div class="four wide required field">
    <div class="ui labeled input">
      <%= f.label "Starting bid", class: "ui label" %>
      <%= f.number_field :price, placeholder: "0.00" %>
    </div>
  </div>

  <div class="seven wide required field">
    <div class="ui labeled input">
      <%= f.label :closing_date, class: "ui label" %>
      <%= f.datetime_field :closing_date, min: Time.zone.now %>
    </div>
  </div>
  
  <div class="required field">
    <div class="ui labeled input">
      <%= f.label "Image", class: "ui label" %>
      <%= f.file_field :img %>
    </div>
  </div>

  <%= f.submit class: "ui teal button" %>

<% end %>

app/views/assets/_sales_segment.html.erb
<% if sales.count != 0 %>
  <div class="ui segment">
    <% if successful %>
      <h3>Successful sales:</h3>
    <% else %>
      <h3> Unsuccessful sales:</h3>
    <% end %>
      <div class="ui large feed">
        <% sales.each do |sale| %>
          <div class="event">
            <div class="label">
              <img class="ui fluid rounded image" src="<%= url_for(sale.img) if sale.img.attached? %>">
            </div>
            <div class="content">
              <div class="summary">
                <% if  successful %>
                <%= link_to sale.owner.username, sale.owner %> won sale for <%= link_to sale.name, sale %>
                <div class="date">
                  on <%= sale.get_closing_date %>
                </div>
                <% else %>
                Sale for <%= link_to sale.name, sale %> closed with no bids
                <div class="date">
                  on <%= sale.get_closing_date %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
<% end %>

app/views/assets/_seller_stats.html.erb
<div class="ui raised segments">

  <div class="ui segment">
    <h3>Your store's total revenue: $<%= @user.get_total_revenue %></h3>
  </div>

  <% if @popular %>
    <div class="ui segment">
      <h3>Most popular sale:</h3>
      <%= link_to @popular.name, @popular %> for <%= @popular.current_asking_price %></p>
    </div>
  <% end %>

  <%= render 'assets/sales_segment', sales: @user.get_successful_sales, successful: true %>
  <%= render 'assets/sales_segment', sales: @user.get_unsuccessful_sales, successful: false %>
</div>

app/views/assets/_user_form.html.erb
<div class="overlay">
  <div class="banner">
    <p>

    <span>
      THE PIRATEBAY
    </span>

  </p>
  </div>

  <div class="login-page">
    <% if user.errors.any? %>
        <div id="error_explanation">
            <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
    <div class="form">
      <%= form_with model: user, local: true, class: "register-form" do |f| %>
        <%= f.text_field :username, placeholder: "username" %>
        <%= f.password_field :password, placeholder: "password" %>
        <%= f.password_field :password_confirmation, placeholder: "password confirmation" %>
        <%= f.submit "Create an Account", class: "buttonnn" %>
        <p class="message">Already registered? <%= link_to "Sign in", login_path%></p>
      <% end %>
    </div>
  </div>
</div>