config/routes.rb
Rails.application.routes.draw do
  # Home page should direct to the sales index page.
  root 'sales#index'

  # Routes for sessions.
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Routes for users.
  resources :users, except: [:index] do
    collection do 
      get ':id/store', to: 'users#store', as: 'store'
    end
  end
  
  get 'signup', to: 'users#new', as: 'signup'  
  
  # Sale resource.
  resources :sales, except: [:destroy]
  
  #resources :bids, only: [:destroy]
  post 'create_bid', to: 'bids#create', as: 'create_bid'
end

app/models/sale.rb
class Sale < ApplicationRecord
  # Buyer/seller relationship. The owner will start as the seller, and once
  # a Sale is complete, the owner will transition to be the buyer.
  belongs_to :seller, :foreign_key => "seller_id", :class_name => "User"
  belongs_to :owner, :foreign_key => "owner_id", :class_name => "User"

  # A Sale can receive many bids.
  has_many :bids

  # ActiveStorage
  has_one_attached :img

  # Return a Sale's seller's name.
  delegate :username, prefix: "seller", to: :seller
  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 1000,
    too_long: "1000 characters is the maximum allowed"}
  validates :price, presence: true


  # A callback on Sale access that checks whether or not a Sale should be closed.
  after_find do |sale|
    if sale.closing_date < Time.zone.now
      sale.close_sale
    end
  end

  # Used by the after_find callback. Closes a Sale.
  def close_sale
    self.active = false
    if winner?
      self.owner = winner?
      self.save
    end
  end

  # Get the last num Bids made on this Sale.
  def get_recent_bids(num)
    self.bids.sort_by {|bid| bid.created_at}.last(num)
  end

  # Returns the last Bid made on this Sale.
  def get_last_bid
    self.bids.max_by {|bid| bid.created_at}
  end

  # Determines the winner by the last Bid made.
  def winner?
    !!get_last_bid ? get_last_bid.user : nil
  end

  # Determines the current bid on the object.
  def current_asking_price
    !!get_last_bid ? get_last_bid.amount : self.price
  end

  # Returns a string representation of the Sale's closing date.
  def get_closing_date
    self.closing_date.strftime("%m/%d/%Y")
  end

  # Returns a string representation of the time remaining until the Sale closes.
  def time_to_close
    timeElapsed = hours_until_close * 3600
    minutes = (timeElapsed / 60) % 60
    hours = (timeElapsed/3600)
    hours.round.to_s + ":" + format("%02d",minutes.round.to_s)
  end

  # Gets the hours until closing time.
  def hours_until_close
    (self.closing_date.to_time - Time.zone.now.to_time) / 1.hours
  end

  # Get a list of Sales that are still active.
  def self.get_open_sales
    Sale.all.select {|sale| sale.active}
  end

  # Get a list of Sales that are no longer active.
  def self.get_closed_sales
    Sale.all.select {|sale| !sale.active}
  end

  # Get a list of open Sales created by seller with id user_id.
  def self.get_open_sales_by_seller(user_id)
    self.get_open_sales.select {|sale| sale.seller_id == user_id}
  end

  # Get a list of closed Sales created by seller with id user_id.
  def self.get_closed_sales_by_seller(user_id)
    self.get_closed_sales.select {|sale| sale.seller_id == user_id}
  end

  def self.search(search)
    if search && search.length > 0
      sale = Sale.get_open_sales.select {|sale| sale.name.downcase.include? search.downcase }
    else
      Sale.get_open_sales
    end
  end

  # returns list of increment amounts relative to current asking price
  def get_bid_increments
    result = [
      self.current_asking_price * 0.1,
      self.current_asking_price * 0.2,
      self.current_asking_price * 0.4,
      self.current_asking_price * 0.6
    ]
    return result.map {|num| num.round(2)}
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  # Before showing, editing, or updating a Sale, look them up.
  before_action :get_sale, only: [:show, :edit, :update]

  # Gets a view with all open Sales on it.
  # GET /sales
  def index
    if !logged_in?
      redirect_to login_path
    else
      @sales = Sale.search(params[:search])
    end
  end

  # Gets a view containing the Sale with given :id.
  # GET /sales/:id
  def show
    @bid = Bid.new
  end

  
  # Gets a view containing a form to create a new Sale.
  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # Creates a new Sale and saves it to the database with the given params.
  # POST /sales
  def create
    @sale = Sale.new(sale_params.merge(seller_id: session[:user_id], owner_id: session[:user_id], active: true))
    if @sale.save
      redirect_to root_path, notice: "Sale successfully created!"
    else
      # redirect_to new_sale_path, alert: "One or more of the fields were filled out incorrectly."
      p @sale.errors.full_messages
      render 'new'
    end
  end

  private
    # Get the Sale associated with :id.
    def get_sale
      @sale = Sale.find(params[:id])
    end

    # Censor the params to make sure no bad guys take control of our app.
    def sale_params
      params.require(:sale).permit(:img, :name, :description, :price, :closing_date)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<% if sale.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%=form_with model: sale, class: "ui form" do |f| %>
  
  <div class="five wide required field">
    <div class="ui labeled input">
      <%= f.label "Item name", class: "ui label" %>
      <%= f.text_field :name, placeholder: "Name" %>
    </div>
  </div>

  <div class="fourteen wide required field">
    <div class="ui labeled input">
    <%= f.label :description, class: "ui label" %>
    <%= f.text_area :description, placeholder: "Description" %>
    </div>
  </div>

  <div class="four wide required field">
    <div class="ui labeled input">
      <%= f.label "Starting bid", class: "ui label" %>
      <%= f.number_field :price, placeholder: "0.00" %>
    </div>
  </div>

  <div class="seven wide required field">
    <div class="ui labeled input">
      <%= f.label :closing_date, class: "ui label" %>
      <%= f.datetime_field :closing_date, min: Time.zone.now %>
    </div>
  </div>
  
  <div class="required field">
    <div class="ui labeled input">
      <%= f.label "Image", class: "ui label" %>
      <%= f.file_field :img %>
    </div>
  </div>

  <%= f.submit class: "ui teal button"%>

<% end %>

app/views/sales/edit.html.erb
<div class="twelve wide centered column">
  <h2>Update your sale</h2>
  <%= render 'assets/sale_form', sale: @sale %>
</div>

app/views/sales/index.html.erb
<div class="twelve wide centered column">
  <h4>Search sales:</h4>
  <div class="ui action left icon input", style="margin-bottom: 20px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
    <%= form_tag(sales_path, method: :get, class: "ui action left icon input") do %>
      <i class="search icon">
      </i>
      <%= text_field_tag(:search, params[:search], placeholder: "Search") %>
      <button class="ui secondary button">Search</button>
    <% end %>
  </div>
  <div class="ui five stackable cards">
    <% @sales.each do |sale| %>
      <%= render 'assets/sale_card', sale: sale %>
    <% end %>
  </div>
  
</div>
  

app/views/sales/new.html.erb
<div class="twelve wide centered column">
  <h2>Create a new sale</h2>
  <%= render 'assets/sale_form', sale: @sale %>
</div>

app/views/sales/show.html.erb
<div class="twelve wide centered column">

  <div class="ui two column horizontally divided grid">

    <div class="eight wide column">
      <h2><%= @sale.name %></h2>
      <h3>seller: <%= link_to @sale.seller.username, @sale.seller %></h3>
      <%= image_tag url_for(@sale.img), class: "ui fluid image" if @sale.img.attached? %>
      <h4>Current asking price: $<%= @sale.current_asking_price %>

      <div class="description">
        <h3>Item Description:</h3>
        <p><%= @sale.description %></p>
      </div>

      <div class="time">
        <% if @sale.active %>
          <h3> The auction will end in <%= @sale.time_to_close %> hours.</h3>
        <% else %>
          <h3>The auction has ended.</h3>
          <p>Winning bid is made by <%= @sale.owner.username %> for $<%= @sale.current_asking_price %></p>
        <% end %>
      </div>

    </div>

    <div class="six wide column">

      <div class="ui centered aligned container">

        <% if logged_in? %>
          <h3>Place your bid!</h3>
          <%= form_with model: @bid, url: create_bid_path do |f| %>
            <div class="action">
              <%= f.select :amount, [1.00, 5.00, 10.00, 15.00, 20.00] %>
              <%= f.hidden_field :sale_id, value: @sale.id %>
              <%= f.submit "Bid"%>
            </div>
          <% end %>
        <% end %>

        <h3>Bidding history:</h3>
        <div class="ui center aligned container">
          <%= render 'assets/bids_feed', bids: @sale.bids.reverse %>
        </div>

      </div>

    </div>

  </div>

</div>