config/routes.rb
Rails.application.routes.draw do
  # Home page should direct to the sales index page.
  root 'sales#index'

  # Routes for sessions.
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Routes for users.
  resources :users, except: [:index] do
    collection do 
      get ':id/store', to: 'users#store', as: 'store'
    end
  end
  
  get 'signup', to: 'users#new', as: 'signup'  
  
  # Sale resource.
  resources :sales, except: [:destroy]
  
  #resources :bids, only: [:destroy]
  post 'create_bid', to: 'bids#create', as: 'create_bid'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThePirateBay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <h1>ThePirateBay</h1>

    <p id="alert"><%= alert %></p>
    <p id="notice"><%= notice %></p>

    <div class="ui two column grid">
      <%= yield %>
      <% if logged_in? %>
      <div class="two wide column">
        <nav class="ui right fixed inverted vertical menu">
          
            <div class="item">
              <img class="ui image" <%= image_tag("Sept-auction.png") %> 
            </div>
            <%= link_to "Home", root_path, {class: "item"} %>
            <%= link_to "My Profile", current_user, {class: "item"} %>
            <%= link_to "My Store", store_users_path(current_user), {class: "item"} %>
            <%= link_to "Sell", new_sale_path, {class: "item"} %>
            <%= link_to "Log Out (#{current_user.username})", logout_path, {class: "item"} %>

        </nav>
      </div>
    <% end %>
    </div>
    <div class="myfooter">
      <div class="ocean">
        <div class="wave"></div>
        <div class="wave"></div>
      </div>
    </div>
  </body>

</html>